M48
; DRILL file {KiCad 8.0.7} date 2025-02-19T05:02:15+0545
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-19T05:02:15+05:45
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X145.895Y-37.24
X194.155Y-35.97
X194.155Y-118.52
M30
